Sorting vector and finding 5 in the list
anjanko/Zadanka-Wszelkie pull request #1
Opened 2018-01-23 15:31 UTC by anjanko

2018-01-23 16:09 UTC, Pawlo94s requested changes
Not bad.

2018-01-23 16:09 UTC, Pawlo94s commented on .gitignore
> +SortingNumbers/.vs/
You forgot to add ".gitignore" too. :)

2018-01-23 16:09 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +}
What do you remember about adding new elements to a vector?
To prevent continuous reallocations you should add 
`sortedV.reserve(v.size());` after creating `sortedV`

2018-01-23 16:09 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +	vector <int> sortedV;
remove whitespace between `vector` and `<int>`

2018-01-23 16:09 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +	for (vector<int>::iterator it = v.begin(); it != v.end(); it++)
Use `auto` when initializing iterators:
`auto it = v.begin();`

2018-01-23 16:09 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +	for (vector<int>::iterator it = v.begin(); it != v.end(); it++)
Correct all cases in this file!

2018-01-23 16:09 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +		if (*it%2)	//if it's odd
Please add whitespaces before, and after `%`

2018-01-23 16:09 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +	while (it != l.end()&&*it!=5)
Readability!
`while (it != l.end() && *it != 5)`

2018-01-23 16:09 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +		vec.push_back(i);
I know it is possible in C++ to not put in braces single line after `for` and `if`,
but it is highly discouraged by most code policies. Please change it.

2018-01-23 16:09 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +	if (*findNumber(l, 5) == 5)
Same as above.

2018-01-23 16:10 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +		vec.push_back(i);
Change it everywhere!

2018-01-23 16:20 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +		if (*it % 2==0)	//if it's even
Please add whitespaces before, and after `==`

2018-01-23 16:48 UTC, anjanko commented
fixed

2018-01-23 16:59 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +	auto itEndOfV = sortedV.end();
What is this?

2018-01-31 13:32 UTC, anjanko commented on SortingNumbers/SortingNumbers/main.cpp
> +	auto itEndOfV = sortedV.end();
it's a vestige of a previous idea

2018-02-01 06:40 UTC, Pawlo94s requested changes

2018-02-01 06:40 UTC, Pawlo94s commented on SortingNumbers/SortingNumbers/main.cpp
> +list<int>::iterator findNumber(list<int> &l, int number)
IDE didn't signal you that "number" variable is unused?

2018-02-07 12:39 UTC, Pawlo94s approved these changes

2018-02-07 12:40 UTC, merged