Threads and casting
anjanko/Zadanka-Wszelkie pull request #2
Opened 2018-02-09 16:33 UTC by anjanko

Zachęcam do komentowania i mięsem rzucania.

2018-02-14 13:31 UTC, Pawlo94s requested changes
Casting not reviewed yet

2018-02-14 13:31 UTC, Pawlo94s commented on FibonacciThreads/FibonacciThreads/main.cpp
> +	}
Why not 
```
cin >> num1;
cin >> num2;
```

2018-02-14 13:31 UTC, Pawlo94s commented on FibonacciThreads/FibonacciThreads/main.cpp
> +	}
Is this necessary to take arguments also this way?
I know you are ambitious, and you want to show that you understand something more than is expected,
but in the future do only stuff that your employer / client requires. Nothing less, nothing more.

2018-02-14 13:31 UTC, Pawlo94s commented on FibonacciThreads/FibonacciThreads/main.cpp
> +	cout << endl;
Fibonacci should return one number, not whole array of numbers.
ex.
 fibonacci(0) = 0
 fibonacci(1) = 1
 fibonacci(2) = 1
 fibonacci(3) = 2
 fibonacci(5) = 5

2018-02-14 13:31 UTC, Pawlo94s commented on FibonacciThreads/FibonacciThreads/main.cpp
> +	string userStr1, userStr2;
Code should be self-explanatory.
Reading variable names that are made of shortcuts really annoys me,
and forces me to dive deeper into code.
ex.
`firstNumber` - instead of `num1`
`firstStringFromInput` - instead of `userStr1`
`isValidInput` - instead of `correct`
`sumMutex` - instead of `mtx`

Same with methods:
`getLeastCommonMultiple` instead of `lcm`
`getGreatestCommonDivisor` instead of `gcd`
`fibonacciSequenceGenerator(int startNumber, int* outputArray)` instead of `fibonacciSequence(int startNum, int* fArray)`

2018-02-14 13:31 UTC, Pawlo94s commented on FibonacciThreads/FibonacciThreads/main.cpp
> +void getCorrectNumbers(int* num1, int* num2, string* userStr1, string* userStr2) {
I think it's useless

2018-02-14 13:31 UTC, Pawlo94s commented on FibonacciThreads/FibonacciThreads/main.cpp
> +int lcmResult;
avoid using global variables

2018-02-14 13:31 UTC, Pawlo94s commented on FibonacciThreads/FibonacciThreads/main.cpp
> +	fArray[0] = 1;	//wiem, ze powinno byc startNum, ale jesli to bedzie np. 2, to nie bedzie wcale ciekawie
Rule 1: Avoid using arrays, when you don't have to use them.
Rule 2: If you have to use array, use vector instead (they are nearly as fast as C-like arrays, they are dynamically allocated, they are compatible with lots of algorithms, and have methods like size().)

2018-02-14 13:31 UTC, Pawlo94s commented on FibonacciThreads/FibonacciThreads/main.cpp
> +std::mutex mtx;
Point for you for using mutex.

2018-02-14 13:31 UTC, Pawlo94s commented on FibonacciThreads/FibonacciThreads/main.cpp
> +		a, b = b, a;
What is this?

2018-02-16 16:28 UTC, Pawlo94s requested changes

2018-02-16 16:28 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	void setString(string& ss) {
Should be` const string& ss`. Do you know why?

2018-02-16 16:28 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +		setString(static_cast<string>("This is string in derived class."));
Is `static_cast ` necessary here?

2018-02-16 16:28 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	float intF = (int)f;
intF is float?

2018-02-16 16:28 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	string strLine = static_cast<string>(line);
casting char array to string is not good example of using static_cast.
There is a better way of doing it.

2018-02-16 16:28 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	cout << "Function myFun takes casted const int as parameter and here is the result: "
ok

2018-02-16 16:28 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +
Where is dynamic_cast?

2018-02-16 16:28 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	DerivedClass* castedBase = reinterpret_cast<DerivedClass*>(&base);
ok

2018-02-17 17:00 UTC, anjanko commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	void setString(string& ss) {
no idea

2018-02-18 11:32 UTC, anjanko commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +		setString(static_cast<string>("This is string in derived class."));
actually I forgot why  I used it...

2018-02-18 11:40 UTC, anjanko commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	float intF = (int)f;
This line has no sense, so let's assume that I wrote there 
float d=6.33;
float divisionResult = (int)d / (int)f;
and now we clearly see how excellently this type of casting works.

2018-02-18 11:54 UTC, anjanko commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	string strLine = static_cast<string>(line);
so there's another example:
int a;
void* pa;
pa=&a;
int b = static_cast<int>(*pa);

2018-02-18 12:13 UTC, anjanko commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	DerivedClass* castedBase = reinterpret_cast<DerivedClass*>(&base);
here:


BaseClass2{
private:
	float f;
public:
	BaseClass2();
	virtual ~BaseClass2();
}

DerivedClass2 : public BaseClass2{
public:
	DerivedClass2();
	~DerivedClass2();
}

DerivedClass2 derived2;
BaseClass* derived2Casted = dynamic_cast<BaseClass*>(derived2);
if(!derived2Casted ){
	std::cout << "Bad cast!";
}

2018-02-18 12:13 UTC, anjanko commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +
here:

BaseClass2{
private:
float f;
public:
BaseClass2();
virtual ~BaseClass2();
}

DerivedClass2 : public BaseClass2{
public:
DerivedClass2();
~DerivedClass2();
}

DerivedClass2 derived2;
BaseClass* derived2Casted = dynamic_cast<BaseClass*>(derived2);
if(!derived2Casted ){
std::cout << "Bad cast!";
}

2018-02-20 11:05 UTC, Pawlo94s approved these changes

2018-02-20 11:05 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	void setString(string& ss) {
To prevent ss from being changed in this method.

2018-02-20 11:05 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +		setString(static_cast<string>("This is string in derived class."));
remove it

2018-02-20 11:05 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	float intF = (int)f;
ugh ok.

2018-02-20 11:05 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +	string strLine = static_cast<string>(line);
It's `int b = static_cast<int>(*pa);`, but yeah, it's good usage.

2018-02-20 11:05 UTC, Pawlo94s commented on TypesCasting/TypesCasting/TypesCastingMain.cpp
> +
ok

2018-02-20 11:05 UTC, Pawlo94s commented on Lambda/Lambda/main.cpp
> +#include <iostream>
Nice and readable code.

2018-02-20 11:05 UTC, Pawlo94s commented on Lambda/Lambda/main.cpp
> +	funVector.reserve(3 * sizeof(std::function<double(double, double)>));
reserve does not operate on bytes. It calculates it automatically.
So it should be just `funVector.reserve(3);`

2018-02-21 19:38 UTC, merged